# Generated by Django 3.2.17 on 2023-02-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_add_enrollment_officer_gql_query_location_right'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthfacility',
            options={'managed': True},
        ),
    ]
