# Generated by Django 3.2.17 on 2023-02-13 11:12

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('medical_pricelist', '0002_itemspricelistmutation_servicespricelistmutation'),
        ('location', '0009_alter_healthfacility_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='program',
            field=models.ForeignKey(db_column='program', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hf_program', to='program.program'),
        )
    ]
