# Generated by Django 3.2.17 on 2023-02-13 19:51

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('medical_pricelist', '0002_itemspricelistmutation_servicespricelistmutation'),
        ('location', '0010_auto_20230213_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacility',
            name='program',
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='program',
            field=models.ManyToManyField(to='program.Program'),
        )
    ]
