# Generated by Django 3.2.23 on 2024-01-04 15:15

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20230317_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='bank_name',
            field=models.CharField(blank=True, db_column='BankName', max_length=255, null=True),
        ),
    ]
