# Generated by Django 3.2.22 on 2023-10-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_set_managed_to_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacility',
            name='row_id',
        ),
        migrations.AddField(
            model_name='healthfacility',
            name='responsible',
            field=models.CharField(blank=True, db_column='HFResponsible', max_length=255, null=True),
        ),
    ]
