# Generated by Django 4.2.17 on 2024-12-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_auto_20230317_0927'),
        ('location', '0019_merge_20241214_1531'),
        ('location', '0020_migrationjsonExt_1516'),
    ]

    operations = [
    ]