# Generated by Django 3.2.16 on 2023-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_healthfacility_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacility',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='json_ext',
            field=models.JSONField(blank=True, db_column='JsonExt', null=True),
        ),
    ]