# Generated by Django 4.2.17 on 2025-02-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_add_location_read_right'),
        ('location', '0010_insert_create_region_location_perms'),
        ('location', '0011_auto_20230317_0924'),
        ('location', '0021_merge_20241214_1542'),
        ('location', '0022_migrationjsonExt_1517'),
    ]

    operations = [
    ]
