# Generated by Django 4.2.17 on 2025-02-08 12:03
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_merge_20250208_1203'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE INDEX idx_user_location_validity 
            ON tblUsersDistricts (UserID, LocationId, ValidityTo);
            """
            if settings.MSSQL else
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.tables
                    WHERE table_name = 'tblusersdistricts'
                ) THEN
                    CREATE INDEX IF NOT EXISTS idx_user_location_validity
                    ON "tblUsersDistricts" ("UserID", "LocationId", "ValidityTo");
                END IF;
            END $$;
            """,
            reverse_sql=(
                """
                DROP INDEX idx_user_location_validity ON tblUsersDistricts;
                """
                if settings.MSSQL else
                """
                DROP INDEX IF EXISTS idx_user_location_validity;
                """
            )
        ),
    ]
