# Generated by Django 4.2.17 on 2025-02-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_merge_20250208_1203'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE INDEX idx_user_location_validity ON tblUsersDistricts (UserID, LocationId, ValidityTo);",
            "DROP INDEX idx_user_location_validity ON tblUsersDistricts;"
        ),
    ]
