# Generated by Django 4.2.17 on 2025-08-26 09:19
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    psql_code = 'select 1'

    dependencies = [
        ('location', '0024_merge_20250208_1203'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE [tblLocations] ALTER COLUMN [JsonExt] NVARCHAR(MAX)'
                          if settings.MSSQL else psql_code,
                          reverse_sql='ALTER TABLE [tblLocations] ALTER COLUMN [JsonExt] TEXT'
                          if settings.MSSQL else psql_code),
    ]

